### ISSUE TITLE
another Prometheus

### ISSUE THREAD

**Issue by tissatussa** [AlexGisi/blue-chess#2]
did you know another chess engine exists called Prometheus ?
see https://github.com/zborffs/Prometheus

it's also written in C++, last change was 2 years ago.
i tried to compile it on Linux but i didn't succeed.

[ i'm on Xubuntu 22.04 ]

**Comment by AlexGisi** [comment]
Thanks for the heads-up; I only checked engines on the CCRL when choosing the name. The other author certainly has seniority on his engine so if he wanted me to change it I would, but for now I'm too lazy :)

Thanks for your other issue (#1) as well, I'm looking at it now.

**Comment by tissatussa** [comment]
> Thanks for your other issue 1 as well, I'm looking at it now

i can imagine this error is hard to solve / reproduce .. i guess it's a memory issue, but i'm not into C++ .. maybe you can create a dev version with logging and let me try that version on my Linux and report ?
